import 'package:randomize/data/countries.dart';
import 'package:randomize/data/elements.dart';
import 'data/Movies.dart';
import 'data/games.dart';
 
  String deckId;
  int count=1;
  int remaining=52;
  List list;
  String image;
  String name;
  String title,poster,year;
  double ratings;
  List<Movie> movieList=List();
  String fact;
  List<Country> countryList=List();
  List<Game> gameList=List();
  List<Elements> elementList=List();
  String pass;